# apiVersion: v1
# kind: Secret
# metadata:
#   name: datasource-secret
# data: 
#   d |
#   apiVersion: 1
#   datasources:
#     - ame: prometheusdata
#       type: prometheus
#       access: direct
#       orgId: 1
#       url: http://prometheus-kube-prometheus-prometheus:9090
#       isDefault: true
#       version: 1
#       editable: false

# ---
{{- if (include "grafana.createAdminSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "grafana.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels: {{- include "grafana.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
type: Opaque
data:
  GF_SECURITY_ADMIN_PASSWORD: {{ ternary (randAlphaNum 10) .Values.admin.password (empty .Values.admin.password) | b64enc | quote }}
{{- end }}
