apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-aaa-postgres-exporter_rev3
data:
  aaa-postgres-exporter_rev3.json: |-
{{ .Files.Get "aaa-postgres-exporter_rev3.json" | indent 4}}