apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-Kubernetes _ Compute Resources _ Namespace (Pods)-1604906337714
data:
  Kubernetes _ Compute Resources _ Namespace (Pods)-1604906337714.json: |-
{{ .Files.Get "Kubernetes _ Compute Resources _ Namespace (Pods)-1604906337714.json" | indent 4}}